default_install_hook_types: [pre-commit, pre-push]

repos:
  - repo: local
    hooks:
      - id: hatch-fmt
        name: hatch fmt
        entry: hatch
        language: system
        args: ["run", "fmt"]
        types: [python]
        pass_filenames: false

      - id: hatch-check
        name: hatch check
        entry: hatch
        language: system
        args: ["run", "check"]
        types: [python]
        pass_filenames: false

      - id: hatch-typecheck
        name: hatch typecheck
        entry: hatch
        language: system
        args: ["run", "typecheck"]
        types: [python]
        pass_filenames: false

      # 建議在 push 時跑完整測試（含 coverage gate）
      - id: hatch-tests
        name: hatch tests (with coverage gate)
        entry: hatch
        language: system
        args: ["run", "test-all"]
        stages: [push]
        pass_filenames: false
